export default [
  {
    title: "Sport Water Bottles Portable Thermoses 500ml",
    category: "bottles",
    quantity: 27,
    brand: "Active",
    image: ["/public/products/bottel1.jpg"],
    price: 450,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title:
      "Stainless Steel Double Wall Vacuum Insulated Water Bottle Thermos 1L",
    category: "bottles",
    quantity: 30,
    brand: "Active",
    image: ["/public/products/bottel2.jpg"],
    price: 250,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Fashion Glasses Travel Cycling Portable Kettle Black 2.2L",
    category: "bottles",
    quantity: 15,
    brand: "Active",
    image: ["./public/products/bottel3.jpg"],
    price: 350,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Fashion Seal Gourde Climbing Water Protein Shaker Grey 400ml",
    category: "bottles",
    quantity: 40,
    brand: "Active",
    image: ["./public/products/bottel4.jpg"],
    price: 400,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: " Sport Gym Protein Shaker Mixer Bottle 600ml",
    category: "bottles",
    quantity: 12,
    brand: "Active",
    image: ["./public/products/bottel5.jpg"],
    price: 600,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Self Omega 3 Fish Oil  540 EPA + 360 DHA",
    category: "Supplements",
    quantity: 100,
    brand: "Active",
    image: ["./public/products/Supplements1.jpg"],
    price: 150,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Whey Protein Powder, French Vanilla Creme, 2 Pound",
    category: "Supplements",
    quantity: 90,
    brand: "Active",
    image: ["./public/products/Supplements2.jpg"],
    price: 1200,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: " MuscleTech Grass Fed Whey Protein Powder 1.8 Pound",
    category: "Supplements",
    quantity: 50,
    brand: "Active",
    image: ["./public/products/Supplements3.jpg"],
    price: 1000,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Vitamin D3 5000iu (125mcg) with Coconut Oil Gluten & Soy Free",
    category: "Supplements",
    quantity: 60,
    brand: "Active",
    image: ["./public/products/Supplements4.jpg"],
    price: 100,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title:
      "Magnesium 250 mg,Supplement for Muscle, Heart, Bone and Nerve Support",
    category: "Supplements",
    quantity: 29,
    brand: "Active",
    image: ["./public/products/Supplements5.jpg"],
    price: 65,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title:
      "Optimum Nutrition Micronized Creatine Monohydrate Powder 120 Servings",
    category: "Supplements",
    quantity: 46,
    brand: "Active",
    image: ["./public/products/Supplements6.jpg"],
    price: 300,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Pull String Resistance Band - 15 LB - Red",
    category: "Resistance band",
    quantity: 18,
    brand: "Active",
    image: ["./public/products/Resistance band1.jpg"],
    price: 60,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Set of 5 Resistance Heavy Duty Workout Exercise Bands",
    category: "Resistance band",
    quantity: 20,
    brand: "Active",
    image: ["./public/products/Resistance band2.jpg"],
    price: 200,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Exercise Resistance Bands Set, Stackable Up to 150 Lbs",
    category: "Resistance band",
    quantity: 7,
    brand: "Active",
    image: ["./public/products/Resistance band3.jpg"],
    price: 300,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Resistance Bands Assist Exercise Workout ",
    category: "Resistance band",
    quantity: 0,
    brand: "Active",
    image: ["./public/products/Resistance band4.jpg"],
    price: 120,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Leather Fashion Fitness High Capacity Shoulder Gym Duffle Bag",
    category: "Bags",
    quantity: 10,
    brand: "Active",
    image: ["./public/products/Bags1.jpg"],
    price: 450,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Fashion Shoulder Sport Large Capacity Waterproof Gym Duffle Bag",
    category: "Bags",
    quantity: 5,
    brand: "Active",
    image: ["./public/products/Bags2.jpg"],
    price: 399,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Outdoor Waterproof Oxford Sports Gym Bags For Men Women",
    category: "Bags",
    quantity: 20,
    brand: "Active",
    image: ["./public/products/Bags3.jpg"],
    price: 250,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "Adidas Lifestyle ESSENTIALS LOGO DUFFEL BAG MEDIUM GN2039",
    category: "Bags",
    quantity: 2,
    brand: "Active",
    image: ["./public/products/Bags4.jpg"],
    price: 700,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title: "25L Waterproof Backpack Women Men's Hiking Backpack ",
    category: "Bags",
    quantity: 8,
    brand: "Active",
    image: ["./public/products/Bags5.jpg"],
    price: 350,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
  {
    title:
      "Brand StActiveores Canvas Gym Bag-Brand StActiveores - Navy & Black",
    category: "Bags",
    quantity: 30,
    brand: "Active",
    image: ["./public/products/Bags6.jpg"],
    price: 120,
    details: {
      box: "1X 500ml Double-wall Insulated Vacuum Flask Stainless Steel Space Series Coke Thermos For Sport Water Bottles Portable Thermoses",
      made: "Made in China",
      color: "Black",
    },
  },
];
